allprojects {
    repositories {
        def MAVEN_CENTRAL = 'https://repo.maven.apache.org/maven2/'
        def GOOGLE_MIRROR_URL_1 = 'https://maven.aliyun.com/repository/google'

        mavenCentral()
        maven {
            url GOOGLE_MIRROR_URL_1
            allowInsecureProtocol false
        }
        maven {
            url MAVEN_CENTRAL
            allowInsecureProtocol false
        }
        google()
    }
}
